language: ruby
rvm:
  - 2.1.5
sudo: false
cache: bundler
#  directories:
#  - vendor/bundle
#  - spec/dummy/vendor/bundl
gemfile: spec/dummy/Gemfile
branches:
  only:
    - master

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script: travis/setup.sh
script: travis/run.sh
