source 'https://rubygems.org'

gem 'rails', '4.1.10'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer',  platforms: :ruby

# various misc useful utilities
gem 'pry-rails'
#gem 'awesome_print'
gem 'oj'
gem 'hashie'
gem 'pry-byebug'
gem 'nokogiri', '1.6.3'

# Vendor assets management
gem 'bower_vendor'

# Should not be required, but might be useful
gem 'webmock'

#
# needed gems for capybara
#
gem 'capybara'
gem 'capybara-ng', path: '../..'
# if using chrome driver
gem 'selenium-webdriver', '3.0.1'
# if using poltergeist driver
gem 'poltergeist'
#gem 'chromedriver-helper'
gem 'capybara-webkit'

#
# test frameworks
#
gem 'rspec-rails'
gem 'cucumber-rails', require: false
